### ISSUE TITLE
Nice work

### ISSUE THREAD

**Issue by lhost25** [mononobi/mail-out#2]
Nice work and works great but the sender only support plain text. Keep showing error if letter is in html.
Another error server doesn't identify office server using office domain as email.
Lastly no from_name instead it shows sender email.

Once again nice effort in bringing this together.

@mononobi

**Comment by mononobi** [comment]
Thank you for trying it out.

Yeah, for now it does not support html body, but it is welcome to add it as a feature.

For the office domain (or any other email provider), you can easily add support 
for it by doing this (we assume our emails have addresses like this `my_email@office.com`):

- edit the `settings.py` file and add your server configurations:

```python
_OFFICE_SERVER = {
    'host': 'SMTP_URL',
    'port': SMTP_PORT
}

SERVERS = {
    'gmail.com': _GOOGLE,
    'microsoft365.com': _OFFICE_365,
    'office365.com': _OFFICE_365,
    'outlook.com': _OFFICE_365,
    'hotmail.com': _OFFICE_365,
    'live.com': _OFFICE_365,
    'msn.com': _MSN,
    'yahoo.com': _YAHOO,
    'ymail.com': _YAHOO,
    # the below line is to be added to available configs
    'office.com': _OFFICE_SERVER
}
```
About the `from_name`, do you mean a way to be able to put sender name inside the email body?
if that's the case, yeah I will add support for it eventually.

**Comment by mononobi** [comment]
> Nice work and works great but the sender only support plain text. Keep showing error if letter is in html. Another error server doesn't identify office server using office domain as email. Lastly no from_name instead it shows sender email.
> 
> Once again nice effort in bringing this together.
> 
> @mononobi

Thank you for trying it out.

Yeah, for now it does not support html body, but it is welcome to add it as a 
feature (or I will add it when I have a bit of time)

For the office domain (or any other email provider), you can easily add support 
for it by doing this (we assume our emails have addresses like this `my_email@office.com`):

- edit the `settings.py` file and add your server configurations:

```python
_OFFICE_SERVER = {
    'host': 'SMTP_URL',
    'port': SMTP_PORT
}

SERVERS = {
    'gmail.com': _GOOGLE,
    'microsoft365.com': _OFFICE_365,
    'office365.com': _OFFICE_365,
    'outlook.com': _OFFICE_365,
    'hotmail.com': _OFFICE_365,
    'live.com': _OFFICE_365,
    'msn.com': _MSN,
    'yahoo.com': _YAHOO,
    'ymail.com': _YAHOO,
    # the below line is to be added to available configs
    'office.com': _OFFICE_SERVER
}
```
About the `from_name`, do you mean a way to be able to put sender name inside the email body?
if that's the case, yeah I will add support for it eventually.

**Comment by lhost25** [comment]
Hello @mononobi i appreciate you for your effort. 

Yeah, for now it does not support html body, but it is welcome to add it as a
feature (or I will add it when I have a bit of time) => **It will be great addition if it's html message.** 

About the from_name, do you mean a way to be able to put sender name inside the email body?
if that's the case, yeah I will add support for it eventually. => **Send from name that will show from name instead of just showing send from email. Kindly find attached to make it more easier to understand.**

<img width="901" alt="Screenshot 2023-01-31 at 12 26 39 AM" src="https://user-images.githubusercontent.com/87344213/215620813-f8f0e8b6-93ec-4ff9-9af5-4128fe082159.png">

**Comment by mononobi** [comment]
OK, I will add html support later.
for the second part, I will try to see whether it's possible or not.

**Comment by lhost25** [comment]
Ok sir. Nice one.

**Comment by lhost25** [comment]
I did tried some settings and i figured a way to add from_name and html letter.

i can share if you permit me @mononobi

**Comment by mononobi** [comment]
> I did tried some settings and i figured a way to add from_name and html letter.
> 
> i can share if you permit me @mononobi 

That's great

Please create a branch from master and commit your changes there, and create a merge request for that. I will take a look at
it and if there were no issues, I will add them to the main branch.

**Comment by mononobi** [comment]
New release with html body and sender name support has been published:

https://github.com/mononobi/mail-out/releases/tag/v0.2
